### ISSUE TITLE
Presentación Grupo 4 DAM

### ISSUE THREAD

**Issue by MarcSantisteban** [CIFP-Pau-Casesnoves-DAW/etv-public-grupo-10-servers#1]
Buenas,
Somos los alumnos de multiplataforma, concretamente el grupo 4.

Hemos estado mirando el Swagger y hemos encontrado una serie de incoherencias (sobretodo en la nomenclatura usada), por ello hemos pensado en usar un formato global para poder entendernos y sincronizarnos.

Este formato seria usar la tipologia de Camel, para los nombres de las variables y que los nombres sean en ingles.

Nos gustaria saber vuestra opinion, un saludo.

**Comment by DimitryCC** [comment]
Buenas

Hemos realizado los cambios la **mayoría** de cambios sugeridos corrigiendo los fallos ortográficos y homogeneizando los nombres. Hemos pasado los cambios de la aplicación a producción y esperamos que se apliquen pronto.

Los cambios realizados son:

1. Hemos corregido las faltas ortográficas.
2. Hemos  homogeneizando los nombres de parámetros y tablas usando la nomenclatura de Camel Case.
3. No hemos traducido los nombres de paramentos ni tablas.

En todo caso existe la posibilidad de que al haber manipulado la base de datos esta no responda satisfactoriamente durante un periodo corto durante el periodo de implementación de los cambios. Aprovechando la ocasión nos gustaría aplicar un protocolo ya que los errores restantes (que esperemos sean escasos o nulos) no serán tan sencillos de encontrar en próximas ocasiones una lista de los errores a corregir.
