### ISSUE TITLE
Estructura Consultes

### ISSUE THREAD

**Issue by xavierllabres1** [CIFP-Pau-Casesnoves-DAW/etv-public-grupo-10-servers#2]
Bones!

Hem trobat una discrepància a l'hora de fer les consultes dels Allotjamets. Concretament el camp descripció, retorna un nombre. 

Ens agradaria saber com ho teniu pensat. Si aquest nombre es una referènia a una descripció a un idioma o si just és una consulta paralela  als allotjaments. Si és així, creim que podria anar tot dins la mateixa consulta. Si no, hauriem de saber com  podem saber quin id equivaldria a quin idioma de quin allotjament.

Salut!

**Comment by DimitryCC** [comment]
Buenas. no te preocupes te dejo aquí un esquema, recordando que el archivo que recibimos un **json**.
ID: 1,  _El id del alojamiento_
nombre: Sloan, _El nombre del alojamiento_
direccion: 447 Del Mar Parkway, _La direccion del alojamiento_
numeroPersonas: 59, _El aforo del alijamiento_
numeroHabitaciones: 15, _Numero de habitaciones_
numeroCamas: 69, _Numero de camas_
numeroBanos: 12, _Numero de baños_
descripcion: 1, _La ID de la descripcion_
tipoAlojamiento: 1, _El ID del tipo de alojamiento_
tipoVacacional: 1, _El ID del tipo vacacional_
categoria: 1, _El ID de la categoria del alojamiento_
municipio: 1, _EL ID del municipio_
usuario: 1 _El ID del usuario_

El idioma es un único idioma al que se referencia en cada descripción (que este escrita en ese idioma).
