### ISSUE TITLE
Token a les consultes informatives.

### ISSUE THREAD

**Issue by xavierllabres1** [CIFP-Pau-Casesnoves-DAW/etv-public-grupo-10-servers#4]
Bones!

Hem vist que ja heu emplenat informació a les descripcions. Però per recuperar la majoria d'elements informatius (recuperar descripcions, valoracions, etc...) hem de mester estar loguejats ja que hem d'enviar el token.

Aquesta informació, no hauria de ser pública? no s'hauria de poder veure la descripció i les valoracions sense estar loguejats?

Salut!

**Comment by DimitryCC** [comment]
Buenas tardes.
Es totalmente **intencional** en no mostrar las descripciones de los alojamientos ni las valoraciones, ya que la API busca **fomentar el uso de las cuentas de usuarios**. El hecho de que no es necesario estar registrado es simplemente para poder tener un _clickbait_ para mejorar la captación de nuevos usuarios, cosa que no necesita ni descripciones ni valoraciones, porque esto interviene en la **idealización** del servicio.

Muchas gracias.
